### ISSUE TITLE
Need to do anything with Alexa skill development?

### ISSUE THREAD

**Issue by csherida** [sfeakes/aqualinkd#1]
is:issue is:open More of a question: how do you expose it as an Alexa skill that the Echo Plus will pick up?  Does it support Zigbee?  Thanks.

**Comment by sfeakes** [comment]
No Zigbee support.
Alexa will depend on how you want to implement it, but ultimately you need to expose either the API end points or a MQTT broker to AWS Lambda.

If you google "Alexa to mqtt" or "Alexa tunneling" there is a lot of information on how to do that. There are other options, but those are probably the easiest. Once that's inlace, you can use the Alexa developer console to configure the endpoints.

If you are using a smart hub, I'd personally connect Aqualinkd to the smart hub on your home network then let the hub communicate to Alexa / AWS Lambda

**Comment by csherida** [comment]
You are awesome sir.  My problem is that my smart hub is Nexia which only supports Zwave which i don’t think works with what you developed. I was thinking of getting the Echo Plus with smart hub built to connect with aqualinkd.  Otherwise, i was going to wrap it like you suggested.

Thanks,
Chris

On Jan 13, 2018, at 10:27 AM, sfeakes <notifications@github.com<mailto:notifications@github.com>> wrote:


No Zigbee support.
Alexa will depend on how you want to implement it, but ultimately you need to expose either the API end points or a MQTT broker to AWS Lambda.

If you google "Alexa to mqtt" or "Alexa tunneling" there is a lot of information on how to do that. There are other options, but those are probably the easiest. Once that's inlace, you can use the Alexa developer console to configure the endpoints.

If you are using a smart hub, I'd personally connect Aqualinkd to the smart hub on your home network then let the hub communicate to Alexa / AWS Lambda
