### ISSUE TITLE
Can i use it together with my iaqualink  IQ20-RS ?

### ISSUE THREAD

**Issue by macmus82** [sfeakes/AqualinkD#22]
I have existing  IQ20-RS but need to integrate this to smarthings. 

Can i connect together with  IQ20-RS to same serial connectors ?

**Comment by sfeakes** [comment]
Yes.  You can add the USBtoRS485 to the same connection / wires you control panel to IQ20-RS (and other devices use).  It’s a RS485 is a buss so you can add multiple devices to it, unlike RS232 (serial) where you can only connect two devices.
AqualinkD is dependent on the control panel version. But if your panel supports IQ20-RS I’m sure it will support AqualinkD.  If your control panel supports the all button keypad then it will support AqualinkD
