### ISSUE TITLE
Can't change name of Aux 1 on web UI

### ISSUE THREAD

**Issue by 42Cyborg** [sfeakes/AqualinkD#230]
Hello, I'm sure I am missing something obvious but my Aux 1 button always says "Cleaner" no matter what I change in the `~/software/AqualinkD/release/aqualinkd.conf`

I want it to say "Spa Blower"
all of the buttons that could possibly be the Aux 1 button are set to spa blower in the aqualinkd.conf and yet it still says cleaner

`button_01_label=Spa Blower

button_02_label=Spa Blower

button_03_label=Spa Blower

button_04_label=Spa Blower`

<img width="150" alt="Screenshot 2023-06-26 at 4 22 12 PM" src="https://github.com/sfeakes/AqualinkD/assets/80754549/f828b7dc-662d-41e2-9abb-e0b10d92a31b">

I am running the prebuilt version on a raspberry pi 4. Let me know if there's any other information that would help diagnose this. Thank you

**Comment by BobClav** [comment]
The file you need to edit is /etc/aqualinkd.conf .  Try that one instead.

**Comment by 42Cyborg** [comment]
That worked, thank you so much! I knew it was something simple
