### ISSUE TITLE
AqualinkD & Homekit

### ISSUE THREAD

**Issue by ericklil** [sfeakes/AqualinkD#31]
Hello,

What great works you have done!
Running HapNodeJS on a Raspi 3, could one run AqualinkD on the same unit or is a separate Raspi suggested?

**Comment by sfeakes** [comment]
You can run it all on a single Pi3 easily.

**Comment by ericklil** [comment]
Many Thanks, look forward to it!

**Comment by ericklil** [comment]
Is there a way to integrate `HapNodeJS` and `AqualinkD` directly instead of using HomeBridge?

**Comment by sfeakes** [comment]
Yes.  Use the Homekit2MQTT configuration in the Wiki.
Homekit2MQTT is a plugin for HapNodeJS that allows for direct MQTT integration. It requires a little more configuration but it's a direct integration without the need for homebridge.

https://github.com/sfeakes/AqualinkD/wiki#HomeKit
