### ISSUE TITLE
make succeeds but error with "sudo make install"

### ISSUE THREAD

**Issue by rpourzia** [sfeakes/AqualinkD#343]
I get the following error with `sudo make install` after successful make. On Debian bookworm
`make: ./release/install.sh: No such file or directory
make: *** [Makefile:279: install] Error 127
`
both the file and directory exist

**Comment by sfeakes** [comment]
What happens when you try to run the command directly 
‘sudo ./release/install.sh‘

**Comment by rpourzia** [comment]
Sorry but by the time I received your reply I had deleted the directory and built again, and it installed fine.  My apologies,
