### ISSUE TITLE
MQTT Temperature Conversion Issue

### ISSUE THREAD

**Issue by tcm0116** [sfeakes/AqualinkD#36]
With `convert_mqtt_temp_to_c` set to `yes`, there is an issue that causes AqualinkD to mis-interpret the incoming temperature setpoints from MQTT on startup.

As can be seen from the log below, AqualinkD almost immediately starts processing MQTT commands after startup. The issue is that AqualinkD has not yet received a temperature message from the controller to determine the units. As such, `_aqualink_data.temp_units` is `UNKNOWN` when the message is received. Line 842 of net_services.c checks to see if `_aqualink_data->temp_units == FAHRENHEIT`, but it's `UNKNOWN` so no conversion is made. `setpoint_check` then checks to see if `_aqualink_data.temp_units == CELSIUS`, but it's still `UNKNOWN` so it compares the setpoint to the min and max values in Fahrenheit.

My recommendation would be to defer processing incoming MQTT messages until after communication has been established with the controller and the state of the system is known.

```Jan 03 19:48:33 aqualink systemd[1]: Started Aqualink RS daemon.
Jan 03 19:48:33 aqualink aqualinkd[22717]: Starting web server on port 80
Jan 03 19:48:33 aqualink aqualinkd[22717]: Starting MQTT client to localhost:1883
Jan 03 19:48:33 aqualink aqualinkd[22717]: Listening to Aqualink RS8 on serial port: /dev/ttyUSB0
Jan 03 19:48:34 aqualink aqualinkd[22717]: Setting setpoint of Spa to 38
Jan 03 19:48:34 aqualink aqualinkd[22717]: Setpoint of 31 for Pool is outside range, using 35
Jan 03 19:48:37 aqualink aqualinkd[22717]: Setting setpoint of Pool to 35
Jan 03 19:48:37 aqualink aqualinkd[22717]: Setting pool heater setpoint to 35
Jan 03 19:48:37 aqualink aqualinkd[22717]: Setting setpoint of Pool to 35
Jan 03 19:48:46 aqualink aqualinkd[22717]: Control Panel B0029223 REV T.2
Jan 03 19:49:04 aqualink aqualinkd[22717]: Getting freeze protection setpoints
Jan 03 19:49:11 aqualink aqualinkd[22717]: Getting pool & spa heat setpoints from aqualink
Jan 03 19:49:40 aqualink aqualinkd[22717]: Setting setpoint of Pool to 87
Jan 03 19:49:43 aqualink aqualinkd[22717]: Setting setpoint of Pool to 87
Jan 03 19:49:43 aqualink aqualinkd[22717]: Setting pool heater setpoint to 87
Jan 03 19:49:43 aqualink aqualinkd[22717]: Setting setpoint of Pool to 87
```

**Comment by sfeakes** [comment]
Thanks.  Should be fixed in 1.2.6a
