### ISSUE TITLE
Spa Mode not updated in Home Assistant Config

### ISSUE THREAD

**Issue by shbatm** [sfeakes/AqualinkD#372]
**EDIT**: Original issue with Spa Mode was due to still having "Spa Mode" as the button name in the config file and an old retained MQTT Topic under `Spa_Mode`. Leaving issue open to capture an update needed to the Home Assistant Config File, will push a PR shortly.

**Comment by sfeakes** [comment]
Thanks for the PR. Spa and Spa_Mode used to be the same depending on panel version, but now with virtual buttons they are two separate things.
BTW, you don;t have to manually configure HA anymore, if you set `mqtt_hassio_discover_topic = homeassistant` in your aqualinkd.conf, AqualinkD will configure HA for you by pushing discoverable devices.  This way you shouldn't have issues in the future.

**Comment by shbatm** [comment]
> BTW, you don;t have to manually configure HA anymore, if you set `mqtt_hassio_discover_topic = homeassistant` in your aqualinkd.conf, AqualinkD will configure HA for you by pushing discoverable devices. This way you shouldn't have issues in the future.

I'm using the Autodiscovery, just cleaning up the old file since I saw it while troubleshooting. My issue with the auto-discovery was a stale retained config entry for `Spa_Mode` on the MQTT Broker, in addition to the new one created at `Spa`--my Home Assistant dashboard was using the old one and it wasn't getting updated when the mode changed.
