### ISSUE TITLE
Question: Light control?

### ISSUE THREAD

**Issue by mikesalz** [sfeakes/AqualinkD#59]
Hello.  This is a question rather than an issue.  Does the Homebridge-AqualinkD plugin control lights?  And if so, is it simply on/off or is there a way to change light color as well?  Thanks in advance!

**Comment by sfeakes** [comment]
Yes it controls the lights, but it's just on / off.  Only the web UI can control the color.  But you can do the manual way of changing color through Homebridge-AqualinkD, ie a series of on/off commands.

**Comment by hollapm** [comment]
Is there a plan to add multi-light control?  IE for pool lights and spa lights if they are on different switches?

**Comment by sfeakes** [comment]
It’s not a feature anyone has asked for until now. I’ll look into it when I get some time.
