### ISSUE TITLE
NEWBIE IAQUALINK B0088 More hardware needed?

### ISSUE THREAD

**Issue by icdoo** [sfeakes/aqualinkd#6]
Sorry if this is a dumb question but I am running a homebridge server and wish to connect to my Jandy Aqualink RS pool controller and use their app. I would like to add control to apple homekit.  I currently use the IAQUALINK B0088 that connects my RS via wifi, do I need additional hardware?

Thanks 
Icdoo

**Comment by sfeakes** [comment]
Yes you will need some computer (like a $10 raspberry pi zero) and an RS485 to USB adapter.  But this only works with AquLinkRS at present, not the AqualinkPDA. I believe The iaqualink can connect to either the Aqualink pda or Aqualink RS, so you need to check the actual Aqualink controller you have
