### ISSUE TITLE
Issue with Serial Port

### ISSUE THREAD

**Issue by xianrecords2015** [sfeakes/AqualinkD#92]
I got a "Aqualink daemon looks like serial error, resetting" and it keeps looping in this before quitting the MQTT process and hanging.

This seems to be the result of line 1110 in aqualinkd.c

rs_fd is not null or negative therefore the port is still opened. It needs to be closed before attempting to re-open it.

I added:
close_serial_port(rs_fd);

after line 1110:         logMessage(LOG_ERR, "Aqualink daemon looks like serial error, resetting.\n");

 And it fixed the issue.

You might want to update the code accordingly.

Thanks for developing this apps. It is really awesome.

Christian

**Comment by sfeakes** [comment]
Thanks very much for the fix, I’ll include it in the next release
